apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tbum
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tbum
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-tbum
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tbum
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tbum
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rqlz-tenant/rhtap-demo-app/hacbs-test-project-tbum@sha256:0d1acbad6710ea517ab940b4951c0617706b8670f128ce77ccb2966fc875d1de
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
