apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tbum
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rqlz-tenant/rhtap-demo-app/hacbs-test-project-tbum@sha256:0d1acbad6710ea517ab940b4951c0617706b8670f128ce77ccb2966fc875d1de
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
